name: Build and Deploy Mule Application

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Rename artifact with commit hash
        run: |
          artifactName1=$(ls target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          artifactName2=$(echo $artifactName1 | sed "s/.jar/.$commitHash.jar/")
          mv $artifactName1 $artifactName2

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: target/*.jar

      - name: Publish to Exchange
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifacts

      - name: Deploy to Anypoint Platform
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
          CONNECTEDAPPCLIENTID: ${{ secrets.CONNECTEDAPPCLIENTID }}
          CONNECTEDAPPCLIENTSECRET: ${{ secrets.CONNECTEDAPPCLIENTSECRET }}
          ANYPOINTPLATFORMCLIENTID: ${{ secrets.ANYPOINTPLATFORMCLIENTID }}
          ANYPOINTPLATFORMCLIENTSECRET: ${{ secrets.ANYPOINTPLATFORMCLIENTSECRET }}
          BUSINESSGROUP: ${{ secrets.BUSINESSGROUP }}
          BUSINESSGROUPID: ${{ secrets.BUSINESSGROUPID }}
          REPLICAS: ${{ secrets.REPLICAS }}
        run: |
          artifactName=$(ls *.jar | head -1)
          mvn mule:deploy -Dmule.artifact=$artifactName -Dusername=$ANYPOINT_USERNAME -Dpassword=$ANYPOINT_PASSWORD
